import os
import re
import subprocess
from flask import Flask, render_template, request, redirect, url_for, jsonify, send_from_directory

app = Flask(__name__)

BASE_PORT = 7681
MAX_SESSIONS = 10
active_sessions = {}  # name -> {'port': int, 'process': subprocess.Popen}

CLAUDE_MD_TEMPLATE = """\
# Analysis: {name}

## Purpose
Users will ask you to design and simulate orbital missions using the `gmatbard` library.
Your job is to write Python scripts that generate GMAT mission scripts, run them, and
produce plots and CSV summaries of the results.

## Working Directory
`/workspace/user_analysis/{name}/` — write everything here. Do not touch files outside
this folder.

## File Organisation
Create a subfolder for each simulation:
```
{name}/
  sim_<short_description>/
    generate.py          # the gmatbard Python script
    mission.script       # the GMAT script (generated by generate.py)
    <SC>_BurnReport.csv  # GMAT output
    <SC>_Ephemeris.oem   # GMAT output
    results.csv          # key results extracted and summarised
    plots/
      orbit.png
      burn_summary.png
      mass_history.png
      ...
```
Use descriptive subfolder names, e.g. `sim_leo_to_geo_hohmann` or `sim_lunar_transfer_v1`.
Move or rename files as needed to keep things tidy.

## Standard Outputs (produce for every simulation)
1. **generate.py** — the gmatbard script. Include comments explaining the mission design.
2. **mission.script** — generated by running generate.py.
3. **results.csv** — a small CSV you write manually summarising key numbers:
   delta-V per maneuver, total delta-V, propellant consumed, final orbit elements,
   transfer time, etc. Always include units in the column headers.
4. **Plots** — save to `plots/` as PNG files. At minimum:
   - Burn summary bar chart (delta-V per maneuver) from BurnReport
   - Mass history over the mission
   - 3D or 2D trajectory if an ephemeris (.oem) file was produced

## gmatbard Library
```python
from gmatbard.high_level import SimBuilder, Starship, MissionSequenceBuilder
```
- Examples: `/gmatbard/examples/` — read these before writing new missions.
- Most complete real mission: `/gmatbard/examples/Aquila_DRM_sim1/phase1_5_724kg_800N280s_120mN1400s.py`
- GMAT HTML reference docs: `/gmatbard/docs/GMAT2025a/help/html/`
- Use the high-level API by default. Drop to low-level only when the high-level API
  cannot express the required behaviour.

## Simulation Workflow
Every generate.py must follow this exact structure:

### 1. Build and run
```python
from gmatbard.high_level import SimBuilder, Starship, MissionSequenceBuilder

sim = SimBuilder(name="MissionName")
vehicle = Starship(sim, name="Sat", ...)
msb = MissionSequenceBuilder(sim.script, vehicle.spacecraft, sim.propagator_name)
# ... add maneuvers ...
msb.finalize()

script_path = sim.generate('sim_leo_to_geo/mission.script')
results = sim.run()   # always use sim.run(), not GmatExecutor directly
print(results)
```

### 2. Parse results
```python
from gmatbard.low_level.result_parsers import ResultParser

parser = ResultParser()
log_data     = parser.parse_log_file(script_path)
report_data  = parser.parse_report_files(script_path, sim.script.reports)
# log_data keys: content, mission_sequence_results, propagation_results, burn_results
# report_data: list of dicts, one per report file (BurnReport, Ephemeris, etc.)
```

### 3. Write results.csv
Extract key numbers from log_data/report_data and write a tidy CSV:
delta-V per maneuver, total delta-V, propellant consumed, final orbit elements,
transfer time. Always include units in column headers (e.g. "delta_v_m_s").

### 4. Generate plots
```python
import os, matplotlib
matplotlib.use('Agg')   # headless — no display in container
import matplotlib.pyplot as plt
from gmatbard.visualization import BurnReportPlotter, EphemerisPlotter, TrajectoryPlotter
from bokeh.io import save
from bokeh.resources import CDN
import plotly.io as pio

os.makedirs('sim_name/plots', exist_ok=True)

# ── BurnReportPlotter (from BurnReport.csv) ──────────────────
bp = BurnReportPlotter('sim_name/Sat_BurnReport.csv')

fig = bp.plot_summary_mpl()                # mass + dv + orbit panels
fig.savefig('sim_name/plots/burn_summary.png', dpi=150, bbox_inches='tight')
plt.close(fig)

fig = bp.plot_dv_mpl()
fig.savefig('sim_name/plots/delta_v.png', dpi=150, bbox_inches='tight')
plt.close(fig)

fig = bp.plot_mass_mpl()
fig.savefig('sim_name/plots/mass_history.png', dpi=150, bbox_inches='tight')
plt.close(fig)

save(bp.plot_summary_bokeh(), filename='sim_name/plots/burn_summary.html', resources=CDN, title='Burn Summary')

# ── EphemerisPlotter (from .dat OMERE ephemeris) ─────────────
ep = EphemerisPlotter('sim_name/Sat_Ephemeris.oem.dat')  # adjust filename as needed

fig = ep.plot_summary_mpl()
fig.savefig('sim_name/plots/ephemeris_summary.png', dpi=150, bbox_inches='tight')
plt.close(fig)

save(ep.plot_summary_bokeh(), filename='sim_name/plots/ephemeris.html', resources=CDN, title='Ephemeris')

# ── TrajectoryPlotter (from .oem ephemeris) ──────────────────
tp = TrajectoryPlotter('sim_name/Sat_Ephemeris.oem')

fig = tp.plot_trajectory_mpl()
fig.savefig('sim_name/plots/trajectory_3d.png', dpi=150, bbox_inches='tight')
plt.close(fig)

pio.write_html(tp.plot_trajectory_plotly(), file='sim_name/plots/trajectory_3d.html', auto_open=False)
save(tp.plot_trajectory_bokeh(), filename='sim_name/plots/trajectory_2d.html', resources=CDN, title='Trajectory')
```
Not every output file exists for every mission type — check before plotting and skip
gracefully if a file is missing.

## Committing Work
Commit after each meaningful step: after a simulation runs successfully, after plots
are saved, after results.csv is written. Small frequent commits are better than one
large commit at the end.
```bash
git -C /workspace add user_analysis/{name}/
git -C /workspace commit -m "sim_name: brief description of what this commit adds"
git -C /workspace push
```

## Reporting gmatbard Issues
Whenever you hit a bug, undocumented behaviour, missing feature, or anything that
causes you to stumble while using gmatbard, append an entry to
`gmatbard_issues.md` in this analysis folder. Create the file if it does not exist.

Use this format for each entry:
```
## <short title>
**Date:** <today's date>
**Location:** <module or method where the issue occurs, e.g. gmatbard.high_level.sim_builder.SimBuilder.run>
**What happened:** <what the code did>
**What was expected:** <what it should have done>
**Workaround:** <what you did instead, or "none found">
```

Commit gmatbard_issues.md whenever you add a new entry. This file is the primary
feedback channel for improving the library.

## ASCII Requirement
GMAT only accepts ASCII characters. All `.script` files and any strings passed to
gmatbard (object names, comments, file paths) must be pure ASCII — no Unicode,
curly quotes, dashes, degree symbols, subscripts, or any non-ASCII character.
This applies to Python scripts as well: avoid non-ASCII in any string that ends up
in a generated .script file.

## Iteration
If a simulation fails or the results look wrong, diagnose from the GMAT output log
before changing the script. Common issues: unit mismatches, stopping condition never
triggered, solver not converging. Check the relevant HTML doc in
`/gmatbard/docs/GMAT2025a/help/html/` before guessing.
"""


def seed_claude_md(name, analysis_path):
    claude_md_path = os.path.join(analysis_path, 'CLAUDE.md')
    if not os.path.exists(claude_md_path):
        with open(claude_md_path, 'w') as f:
            f.write(CLAUDE_MD_TEMPLATE.format(name=name))


def sanitize_name(name):
    """Restrict an analysis name to a safe slug: strip whitespace, spaces to
    underscores, then keep only alphanumerics, underscore, and hyphen. Returns
    '' if nothing survives. Applied on EVERY route so a name can never carry a
    path separator or shell metacharacter into the filesystem or a subprocess."""
    name = (name or '').strip().replace(' ', '_')
    return re.sub(r'[^a-zA-Z0-9_-]', '', name)


def get_next_port():
    used = {s['port'] for s in active_sessions.values()}
    for p in range(BASE_PORT, BASE_PORT + MAX_SESSIONS):
        if p not in used:
            return p
    return None


def session_env():
    """Environment for the interactive claude session, with secrets stripped.

    The session (ttyd -> bash -> claude) would otherwise inherit Flask's full
    environment, letting the sandboxed agent read tokens/keys with `env`.
    Removing GITHUB_TOKEN here is safe: git push authenticates via the
    credential store (~/.git-credentials), not this variable.

    ANTHROPIC_API_KEY is deliberately KEPT: interactive OAuth login is not
    working, so claude-code authenticates via this key and must see it in its
    env. This means the agent can read its own key — unavoidable when the key
    is what authenticates the agent itself. Use a scoped/low-budget key.
    """
    keep = {'ANTHROPIC_API_KEY'}
    env = os.environ.copy()
    for key in list(env):
        upper = key.upper()
        if upper in keep:
            continue
        if (upper in ('GITHUB_TOKEN', 'GMATBARD_GITHUB_TOKEN')
                or upper.endswith('_TOKEN')
                or upper.endswith('_KEY')
                or 'SECRET' in upper):
            env.pop(key, None)
    return env


def spawn_ttyd(name, analysis_path):
    port = get_next_port()
    if port is None:
        return None
    # Constant argv — the analysis path is passed as the subprocess cwd, never
    # interpolated into a shell string. ttyd's child bash inherits this cwd.
    cmd = [
        'ttyd', '-p', str(port), '--writable',
        'bash', '-c', 'exec claude'
    ]
    proc = subprocess.Popen(
        cmd, cwd=analysis_path, env=session_env(),
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL
    )
    active_sessions[name] = {'port': port, 'process': proc}
    return port


def ensure_session(name):
    """Start a ttyd session for name if not already running."""
    name = sanitize_name(name)
    if not name:
        return None
    if name in active_sessions:
        proc = active_sessions[name]['process']
        if proc.poll() is None:  # still running
            return active_sessions[name]['port']
        else:
            del active_sessions[name]
    analysis_path = f'/workspace/user_analysis/{name}'
    os.makedirs(analysis_path, exist_ok=True)
    seed_claude_md(name, analysis_path)
    return spawn_ttyd(name, analysis_path)


@app.route('/')
def index():
    return render_template('index.html')


@app.route('/open', methods=['POST'])
def open_analysis():
    name = sanitize_name(request.form.get('name', ''))
    if not name:
        return redirect(url_for('index'))

    analysis_path = f'/workspace/user_analysis/{name}'
    os.makedirs(analysis_path, exist_ok=True)
    seed_claude_md(name, analysis_path)

    # Spawn ttyd if not already running
    ensure_session(name)

    return redirect(url_for('workspace', name=name))


@app.route('/workspace/<name>')
def workspace(name):
    name = sanitize_name(name)
    if not name:
        return redirect(url_for('index'))
    port = ensure_session(name)
    host = request.host.split(':')[0]
    return render_template('workspace.html', name=name, port=port, host=host)


@app.route('/api/files/<name>')
def api_files(name):
    name = sanitize_name(name)
    if not name:
        return jsonify([])
    base_path = f'/workspace/user_analysis/{name}'
    if not os.path.isdir(base_path):
        return jsonify([])

    entries = []
    for dirpath, dirnames, filenames in os.walk(base_path):
        # Add directories
        for dirname in dirnames:
            abs_path = os.path.join(dirpath, dirname)
            rel_path = os.path.relpath(abs_path, base_path)
            entries.append({
                'path': rel_path,
                'size': 0,
                'is_dir': True
            })
        # Add files
        for filename in filenames:
            abs_path = os.path.join(dirpath, filename)
            rel_path = os.path.relpath(abs_path, base_path)
            try:
                size = os.path.getsize(abs_path)
            except OSError:
                size = 0
            entries.append({
                'path': rel_path,
                'size': size,
                'is_dir': False
            })

    # Sort: directories first, then files, both alphabetically
    entries.sort(key=lambda e: (not e['is_dir'], e['path'].lower()))
    return jsonify(entries)


@app.route('/files/<name>/<path:filepath>')
def serve_file(name, filepath):
    name = sanitize_name(name)
    if not name:
        return ('Not found', 404)
    base_path = f'/workspace/user_analysis/{name}'
    _, ext = os.path.splitext(filepath)
    ext = ext.lower()
    if ext in {'.txt', '.py', '.script', '.log', '.md', '.csv', '.json', '.yaml', '.yml'}:
        return send_from_directory(base_path, filepath, mimetype='text/plain')
    elif ext in {'.html', '.htm'}:
        return send_from_directory(base_path, filepath, mimetype='text/html')
    elif ext in {'.png', '.jpg', '.jpeg', '.gif', '.svg', '.webp'}:
        return send_from_directory(base_path, filepath)  # Flask infers image MIME type
    else:
        return send_from_directory(base_path, filepath, as_attachment=True)


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8080, debug=False)
