import os
import re
import subprocess
from flask import Flask, render_template, request, redirect, url_for, jsonify, send_from_directory

app = Flask(__name__)

BASE_PORT = 7681
MAX_SESSIONS = 10
active_sessions = {}  # name -> {'port': int, 'process': subprocess.Popen}

CLAUDE_MD_TEMPLATE = """\
# Analysis: {name}

## Purpose
Users will ask you to design and simulate orbital missions using the `gmatbard` library.
Your job is to write Python scripts that generate GMAT mission scripts, run them, and
produce plots and CSV summaries of the results.

## Working Directory
`/workspace/user_analysis/{name}/` — write everything here. Do not touch files outside
this folder.

## File Organisation
Create a subfolder for each simulation:
```
{name}/
  sim_<short_description>/
    generate.py          # the gmatbard Python script
    mission.script       # the GMAT script (generated by generate.py)
    <SC>_BurnReport.csv  # GMAT output
    <SC>_Ephemeris.oem   # GMAT output
    results.csv          # key results extracted and summarised
    plots/
      orbit.png
      burn_summary.png
      mass_history.png
      ...
```
Use descriptive subfolder names, e.g. `sim_leo_to_geo_hohmann` or `sim_lunar_transfer_v1`.
Move or rename files as needed to keep things tidy.

## Standard Outputs (produce for every simulation)
1. **generate.py** — the gmatbard script. Include comments explaining the mission design.
2. **mission.script** — generated by running generate.py.
3. **results.csv** — a small CSV you write manually summarising key numbers:
   delta-V per maneuver, total delta-V, propellant consumed, final orbit elements,
   transfer time, etc. Always include units in the column headers.
4. **Plots** — save to `plots/` as PNG files. At minimum:
   - Burn summary bar chart (delta-V per maneuver) from BurnReport
   - Mass history over the mission
   - 3D or 2D trajectory if an ephemeris (.oem) file was produced

## gmatbard Library
```python
from gmatbard.high_level import SimBuilder, Starship, MissionSequenceBuilder
```
- Examples: `/gmatbard/examples/` — read these before writing new missions.
- Most complete real mission: `/gmatbard/examples/Aquila_DRM_sim1/phase1_5_724kg_800N280s_120mN1400s.py`
- GMAT HTML reference docs: `/gmatbard/docs/GMAT2025a/help/html/`
- Use the high-level API by default. Drop to low-level only when the high-level API
  cannot express the required behaviour.

## Running a Simulation
```python
# 1. Generate the .script file
sim.generate('sim_name/mission.script')

# 2. Execute it
from gmatbard.low_level.script_execution import GmatExecutor
result = GmatExecutor().execute('sim_name/mission.script')
print(result.stdout)
```
`GmatConsole` is on PATH. GMAT outputs (BurnReport, Ephemeris) are written to the
directory where the .script file lives.

## Plotting
```python
from gmatbard.visualization.burn_plots import BurnReportPlotter
from gmatbard.visualization.trajectory_plots import plot_trajectory_3d  # check exact API

plotter = BurnReportPlotter('sim_name/Sat_BurnReport.csv')
fig = plotter.plot_burn_summary()          # returns a matplotlib Figure
fig.savefig('sim_name/plots/burn_summary.png', dpi=150, bbox_inches='tight')
```
Always call `plt.close(fig)` or `matplotlib.pyplot.close('all')` after saving so
figures don't accumulate in memory across multiple runs.

## Committing Work
Commit after each meaningful step: after a simulation runs successfully, after plots
are saved, after results.csv is written. Small frequent commits are better than one
large commit at the end.
```bash
git -C /workspace add user_analysis/{name}/
git -C /workspace commit -m "sim_name: brief description of what this commit adds"
git -C /workspace push
```

## ASCII Requirement
GMAT only accepts ASCII characters. All `.script` files and any strings passed to
gmatbard (object names, comments, file paths) must be pure ASCII — no Unicode,
curly quotes, dashes, degree symbols, subscripts, or any non-ASCII character.
This applies to Python scripts as well: avoid non-ASCII in any string that ends up
in a generated .script file.

## Iteration
If a simulation fails or the results look wrong, diagnose from the GMAT output log
before changing the script. Common issues: unit mismatches, stopping condition never
triggered, solver not converging. Check the relevant HTML doc in
`/gmatbard/docs/GMAT2025a/help/html/` before guessing.
"""


def seed_claude_md(name, analysis_path):
    claude_md_path = os.path.join(analysis_path, 'CLAUDE.md')
    if not os.path.exists(claude_md_path):
        with open(claude_md_path, 'w') as f:
            f.write(CLAUDE_MD_TEMPLATE.format(name=name))


def get_next_port():
    used = {s['port'] for s in active_sessions.values()}
    for p in range(BASE_PORT, BASE_PORT + MAX_SESSIONS):
        if p not in used:
            return p
    return None


def spawn_ttyd(name, analysis_path):
    port = get_next_port()
    if port is None:
        return None
    cmd = [
        'ttyd', '-p', str(port), '--writable',
        'bash', '-c',
        f'cd {analysis_path} && exec claude'
    ]
    proc = subprocess.Popen(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    active_sessions[name] = {'port': port, 'process': proc}
    return port


def ensure_session(name):
    """Start a ttyd session for name if not already running."""
    if name in active_sessions:
        proc = active_sessions[name]['process']
        if proc.poll() is None:  # still running
            return active_sessions[name]['port']
        else:
            del active_sessions[name]
    analysis_path = f'/workspace/user_analysis/{name}'
    os.makedirs(analysis_path, exist_ok=True)
    seed_claude_md(name, analysis_path)
    return spawn_ttyd(name, analysis_path)


@app.route('/')
def index():
    return render_template('index.html')


@app.route('/open', methods=['POST'])
def open_analysis():
    name = request.form.get('name', '')
    # Sanitize: strip whitespace, replace spaces with underscores, keep only alphanumeric/underscore/hyphen
    name = name.strip().replace(' ', '_')
    name = re.sub(r'[^a-zA-Z0-9_-]', '', name)
    if not name:
        return redirect(url_for('index'))

    analysis_path = f'/workspace/user_analysis/{name}'
    os.makedirs(analysis_path, exist_ok=True)
    seed_claude_md(name, analysis_path)

    # Spawn ttyd if not already running
    ensure_session(name)

    return redirect(url_for('workspace', name=name))


@app.route('/workspace/<name>')
def workspace(name):
    port = ensure_session(name)
    return render_template('workspace.html', name=name, port=port)


@app.route('/api/files/<name>')
def api_files(name):
    base_path = f'/workspace/user_analysis/{name}'
    if not os.path.isdir(base_path):
        return jsonify([])

    entries = []
    for dirpath, dirnames, filenames in os.walk(base_path):
        # Add directories
        for dirname in dirnames:
            abs_path = os.path.join(dirpath, dirname)
            rel_path = os.path.relpath(abs_path, base_path)
            entries.append({
                'path': rel_path,
                'size': 0,
                'is_dir': True
            })
        # Add files
        for filename in filenames:
            abs_path = os.path.join(dirpath, filename)
            rel_path = os.path.relpath(abs_path, base_path)
            try:
                size = os.path.getsize(abs_path)
            except OSError:
                size = 0
            entries.append({
                'path': rel_path,
                'size': size,
                'is_dir': False
            })

    # Sort: directories first, then files, both alphabetically
    entries.sort(key=lambda e: (not e['is_dir'], e['path'].lower()))
    return jsonify(entries)


@app.route('/files/<name>/<path:filepath>')
def serve_file(name, filepath):
    base_path = f'/workspace/user_analysis/{name}'
    _, ext = os.path.splitext(filepath)
    ext = ext.lower()
    if ext in {'.txt', '.py', '.script', '.log', '.md', '.csv', '.json', '.yaml', '.yml'}:
        return send_from_directory(base_path, filepath, mimetype='text/plain')
    elif ext in {'.html', '.htm'}:
        return send_from_directory(base_path, filepath, mimetype='text/html')
    else:
        return send_from_directory(base_path, filepath, as_attachment=True)


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8080, debug=False)
